import { randomBytes } from "node:crypto";
import { access, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import mysql from "mysql2";
import { hash } from "bcryptjs";

// Chỉ xuất file SQL, không kết nối hoặc ghi vào bất kỳ database nào.
// File và thông tin đăng nhập được tạo trong .local/ (đã nằm trong .gitignore).
const output = resolve(process.argv[2] || ".local/admin-chef-db.sql");
const credentialsFile = output.replace(/\.sql$/i, ".credentials.txt");

for (const file of [output, credentialsFile]) {
  try {
    await access(file);
    throw new Error(`File đã tồn tại: ${file}. Hãy chọn tên file khác.`);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
}

type Raw = { raw: string };
const raw = (value: string): Raw => ({ raw: value });
const value = (input: string | number | boolean | null | Raw) =>
  typeof input === "object" && input !== null && "raw" in input
    ? input.raw
    : mysql.escape(input as string | number | boolean | null);

const insert = (
  table: string,
  columns: string[],
  values: (string | number | boolean | null | Raw)[],
) =>
  `INSERT IGNORE INTO ${table} (${columns.join(",")}) VALUES (${values
    .map(value)
    .join(",")});`;

const upsertPlatformSetting = (id: string, json: Raw) =>
  `INSERT INTO platform_settings (id,value) VALUES (${value(id)},${value(
    json,
  )}) ON DUPLICATE KEY UPDATE value=VALUES(value);`;

const now = raw("UTC_TIMESTAMP(3)");
const serviceDate = raw(
  "DATE(DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 7 HOUR))",
);
const inDays = (days: number) =>
  raw(`DATE_ADD(UTC_TIMESTAMP(3), INTERVAL ${days} DAY)`);
const cutoff = (time: string, offset: number) =>
  raw(
    `DATE_SUB(TIMESTAMP(DATE_ADD(DATE(DATE_ADD(UTC_TIMESTAMP(3), INTERVAL 7 HOUR)), INTERVAL ${offset} DAY), '${time}:00'), INTERVAL 7 HOUR)`,
  );

const password = randomBytes(24).toString("base64url");
const passwordHash = await hash(password, 12);
const photo = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`;

const statements: string[] = [
  "-- Generated by npm run db:seed:export:admin-chef",
  "-- Contains the complete schema plus one admin and one approved chef.",
  "-- Do not commit this file or the credentials file.",
  "-- INSERT IGNORE preserves existing account passwords. New credentials apply only to newly inserted accounts.",
  "CREATE DATABASE IF NOT EXISTS toigibanthe CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
  "USE toigibanthe;",
  "SET NAMES utf8mb4;",
];

const databaseDir = new URL("../database/", import.meta.url);
for (const file of (await readdir(databaseDir))
  .filter((name) => name.endsWith(".sql"))
  .sort()) {
  statements.push(`-- ${file}`);
  statements.push((await readFile(new URL(file, databaseDir), "utf8")).trim());
}

statements.push(
  insert(
    "users",
    [
      "id",
      "name",
      "email",
      "password_hash",
      "phone",
      "role",
      "active",
      "created_at",
    ],
    [
      "demo-admin",
      "Quản trị viên",
      "admin@toigibando.local",
      passwordHash,
      "0900000000",
      "admin",
      true,
      now,
    ],
  ),
  insert(
    "users",
    [
      "id",
      "name",
      "email",
      "password_hash",
      "phone",
      "role",
      "active",
      "created_at",
    ],
    [
      "demo-chef-user",
      "Minh Anh",
      "chef@toigibando.local",
      passwordHash,
      "0900000001",
      "chef",
      true,
      now,
    ],
  ),
  insert(
    "chefs",
    [
      "id",
      "user_id",
      "name",
      "bio",
      "address",
      "area",
      "lat",
      "lng",
      "radius_km",
      "status",
      "avatar_url",
      "rating",
      "rating_count",
      "completed_orders",
      "created_at",
    ],
    [
      "demo-chef",
      "demo-chef-user",
      "Bếp Minh Anh",
      "Cơm nhà và món Việt, nấu mới mỗi bữa.",
      "45 Nguyễn Đình Chiểu, Quận 3, TP. Hồ Chí Minh",
      "Quận 3",
      10.7862,
      106.6941,
      5,
      "approved",
      photo("photo-1580489944761-15a19d654956"),
      4.8,
      36,
      84,
      now,
    ],
  ),
  insert(
    "campaigns",
    ["id", "name", "active", "starts_at", "ends_at", "created_at"],
    [
      "demo-campaign",
      "Ưu đãi thực đơn hôm nay",
      true,
      inDays(-1),
      inDays(7),
      now,
    ],
  ),
  insert(
    "kitchen_sessions",
    ["id", "chef_id", "service_date", "is_open", "created_at"],
    ["demo-session", "demo-chef", serviceDate, true, now],
  ),
  insert(
    "banners",
    ["id", "title", "body", "image_url", "href", "active", "sort_order"],
    [
      "demo-banner",
      "Thực đơn hôm nay",
      "Xem món đang được Bếp Minh Anh nhận đặt.",
      null,
      "/nearby",
      true,
      0,
    ],
  ),
  upsertPlatformSetting(
    "delivery",
    raw("JSON_OBJECT('baseFee',15000,'perKm',0)"),
  ),
  upsertPlatformSetting(
    "support",
    raw("JSON_OBJECT('email','hotro@toigibando.vn','phone','')"),
  ),
  insert(
    "vouchers",
    [
      "id",
      "code",
      "title",
      "chef_id",
      "discount_amount",
      "min_subtotal",
      "max_uses",
      "used_count",
      "expires_at",
      "active",
    ],
    [
      "demo-voucher",
      "BEP10",
      "Giảm 10.000đ tại Bếp Minh Anh",
      "demo-chef",
      10000,
      50000,
      100,
      0,
      inDays(30),
      true,
    ],
  ),
  insert(
    "notifications",
    [
      "id",
      "user_id",
      "category",
      "title",
      "body",
      "href",
      "is_read",
      "created_at",
    ],
    [
      "demo-admin-welcome",
      "demo-admin",
      "news",
      "Database mẫu đã sẵn sàng",
      "Bạn có thể mở mục Chefs để kiểm tra Bếp Minh Anh.",
      "/admin",
      false,
      now,
    ],
  ),
);

const foods = [
  [
    "demo-product-1",
    "Cơm gà sốt gừng",
    "Cơm nóng, gà áp chảo và rau theo ngày.",
    45000,
    "photo-1547592180-85f173990554",
    "lunch",
    "11:00",
    0,
    10000,
  ],
  [
    "demo-product-2",
    "Bún bò Huế",
    "Bún bò và nước dùng hầm trong ngày.",
    55000,
    "photo-1555126634-323283e090fa",
    "lunch",
    "15:00",
    0,
    null,
  ],
  [
    "demo-product-3",
    "Bánh mì trứng",
    "Bánh mì giòn, trứng và rau tươi.",
    25000,
    "photo-1525351484163-7529414344d8",
    "breakfast",
    "11:00",
    0,
    null,
  ],
  [
    "demo-product-4",
    "Cơm sườn nướng",
    "Sườn nướng, cơm trắng và đồ chua.",
    49000,
    "photo-1511690743698-d9d85f2fbf38",
    "dinner",
    "21:00",
    0,
    null,
  ],
] as const;

for (let index = 0; index < foods.length; index += 1) {
  const [id, name, description, price, image, meal, cutoffTime, dayOffset, discount] =
    foods[index];
  statements.push(
    insert(
      "products",
      [
        "id",
        "chef_id",
        "name",
        "description",
        "ingredients",
        "price",
        "image_url",
        "rating",
        "rating_count",
        "created_at",
      ],
      [
        id,
        "demo-chef",
        name,
        description,
        "Liên hệ bếp nếu bạn có dị ứng thực phẩm.",
        price,
        photo(image),
        4.7,
        12 + index * 4,
        now,
      ],
    ),
    insert(
      "daily_menu",
      [
        "id",
        "session_id",
        "product_id",
        "meal_id",
        "cutoff_at",
        "stock",
        "sale_price",
        "campaign_id",
        "enabled",
      ],
      [
        `demo-menu-${index + 1}`,
        "demo-session",
        id,
        meal,
        cutoff(cutoffTime, dayOffset),
        20,
        discount === null ? null : price - discount,
        discount === null ? null : "demo-campaign",
        true,
      ],
    ),
  );
}

await mkdir(dirname(output), { recursive: true });
await writeFile(output, statements.join("\n\n") + "\n", {
  flag: "wx",
  mode: 0o600,
});
await writeFile(
  credentialsFile,
  [
    "Tài khoản database mẫu",
    "Admin: admin@toigibando.local",
    "Chef: chef@toigibando.local",
    `Mật khẩu dùng chung: ${password}`,
    "",
    "Chef: Bếp Minh Anh, trạng thái approved, bán kính giao 5 km.",
    "Không nhập thông tin ngân hàng thật vào dữ liệu mẫu.",
    "Giữ file này riêng; không commit hoặc gửi lên chat.",
  ].join("\n") + "\n",
  { flag: "wx", mode: 0o600 },
);

console.log(`Đã tạo SQL đầy đủ schema + seed: ${output}`);
console.log(`Thông tin đăng nhập riêng: ${credentialsFile}`);
console.log("Nếu tài khoản mẫu đã tồn tại, INSERT IGNORE không đổi mật khẩu. Dùng db:seed:repair:credentials để xuất SQL đồng bộ.");
